update init script

diff --git a/pppoe b/pppoe
--- a/pppoe
+++ b/pppoe
@@ -1,46 +1,96 @@
-process=$(pgrep pppoe)
-path_to_script="/opt/scripts/pppoe.sh"
-path_to_log="/var/log/pppoe.log"
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides: pppoe
+# Required-Start: $remote_fs $syslog
+# Required-Stop: $remote_fs $syslog
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: Start daemon at
+# boot time Description: Enable service provided by daemon.
+### END INIT INFO
 
-case $1 in
+dir="/opt/scripts"
+cmd="./pppoe.sh"
+user=""
+name=`basename $0`
+
+pid_file="/var/run/$name.pid"
+stdout_log="/var/log/$name.log"
+stderr_log="/var/log/$name.err"
+
+get_pid() {
+    cat "$pid_file"
+}
+
+is_running() {
+    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
+}
+
+case "$1" in
     start)
-        if [ -z $process ]; then
-            $path_to_script >> $path_to_log &
-	    echo "Starting PPPOE OK"
+    if is_running; then
+        echo "Already started"
+    else
+        echo "Starting $name"
+        cd "$dir"
+        if [ -z "$user" ]; then
+            $cmd >> "$stdout_log" 2>> "$stderr_log" &
         else
-            echo "ERROR"
-            echo "PPPOE alredy running"
+            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
         fi
+        echo $! > "$pid_file"
+        if ! is_running; then
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            exit 1
+        fi
+    fi
     ;;
-
     stop)
-        if [ -z $process ]; then
-            echo "ERROR"
-            echo "PPPOE is no running"
+    if is_running; then
+        echo -n "Stopping $name.."
+        kill `get_pid`
+        for i in 1 2 3 4 5 6 7 8 9 10
+        # for i in `seq 10`
+        do
+            if ! is_running; then
+                break
+            fi
+            echo -n "."
+            sleep 1
+        done
+        echo
+        if is_running; then
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            exit 1
         else
-            echo "Stoping PPPOE OK"
-            kill -9 $process > /dev/null 2>&1
+            echo "Stopped"
+            if [ -f "$pid_file" ]; then
+                rm "$pid_file"
+            fi
         fi
+    else
+        echo "Not running"
+    fi
     ;;
-
     restart)
-        kill -9 $process > /dev/null 2>&1
-	$path_to_script >> $path_to_log &
-        echo "Restarting PPPOE OK"
+    $0 stop
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
+        exit 1
+    fi
+    $0 start
     ;;
-
     status)
-        if [ -z $process ]; then
-            echo "PPPOE is no running"
-        else
-            echo "PPPOE running"
-	    echo "PPPOE: $process"
-	fi
+    if is_running; then
+        echo "Running"
+    else
+        echo "Stopped"
+        exit 1
+    fi
     ;;
     *)
-        echo "Usage /etc/init.d/ddns start|stop|restart|status"
-        exit 1
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
     ;;
-
 esac
-
+exit 0
